---
- hosts: localhost
  become: true
  vars:
    tower_url: https://ansible_tower_ip
    tower_token: your_token
    tower_validate_certs: no
    c_rh_c_host: "ci.cloud.redhat.com"
    rhn_subscription_url: "https://subscription.rhsm.qa.redhat.com/subscription"
    skip_systemd: 1
  roles:
    - mkanoor.catalog_receptor_installer
