---
- hosts: localhost
  become: true
  vars:
    tower_url: "https://ansible_tower_ip"
    tower_user: "admin"
    tower_password: "secret"
    tower_validate_certs: no
    skip_systemd: 1
  roles:
    - mkanoor.catalog_receptor_installer
